# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=5)),
                ('thema', models.CharField(max_length=30)),
                ('variabele', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=65)),
                ('definitie', models.TextField()),
                ('bron', models.CharField(max_length=50)),
                ('peildatum', models.CharField(max_length=50)),
                ('verschijningsfrequentie', models.CharField(max_length=50)),
                ('eenheid', models.IntegerField(null=True)),
                ('groep', models.CharField(max_length=50, null=True)),
                ('format', models.CharField(max_length=5, null=True)),
                ('thema_kleurentabel', models.CharField(max_length=50, null=True)),
                ('kleurenpalet', models.IntegerField(null=True)),
                ('minimum_aantal_inwoners', models.IntegerField(null=True)),
                ('minimum_aantal_woningen', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variabelen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.IntegerField()),
                ('gebiedcode15', models.CharField(max_length=4)),
                ('variabele', models.CharField(max_length=30)),
                ('waarde', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='variabelen',
            unique_together=set([('jaar', 'gebiedcode15', 'variabele')]),
        ),
        migrations.AlterIndexTogether(
            name='variabelen',
            index_together=set([('jaar', 'gebiedcode15'), ('gebiedcode15', 'variabele')]),
        ),
    ]
