# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbga_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijfers',
            name='gebiedcode15',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='cijfers',
            name='jaar',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cijfers',
            name='variabele',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
