# Generated by Django 2.1.7 on 2019-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbga_data', '0002_auto_20170720_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='definition',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='frequency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='label_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='label_kort',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='reference_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='topic',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='tussenkop_kerncijfertabel',
            field=models.CharField(max_length=65, null=True),
        ),
    ]

