# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbga_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='legendacode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='symbool',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
